#model_name: resnet18
#task: classification
#backbone: resnet18
#verbose: false
#debug: false
#return_path: false

rel_path: cv/classification/resnet18/resnet18_torch
ModelZoo_path: /workspace/public/basemodel/${rel_path}
SrcCode_path: ${rel_path}
Build_path: build/${rel_path}

####################################
torch:
  inherit: build_torch
  pretrained:
    model_path: ${ModelZoo_path}/resnet18-5c106cde.pth

build_torch:
  model_path: null
  verbose: false

####################################
onnx:
  pretrained:
    model_path: ${ModelZoo_path}/resnet18_3x224x224_b0.onnx
    input_shape:
      - 3
      - 224
      - 224
    batch_size: -1
    opset_version: 11
  return_path: null

build_onnx:
  verbose: false
  torch_model_path: null
  batch_size: -1
  input_shape:
    - 3
    - 224
    - 224
  onnx_model_path: ${Build_path}/resnet18_3x224x224_b0.onnx

####################################
trt:
  pretrained:
    int8:
      precision: int8
      model_path: ${ModelZoo_path}/trt/resnet18-5c106cde_batch8_int8.trt
      batch_size: 8
      input_shape:
        - 3
        - 224
        - 224
    fp16:
      precision: fp16
      model_path: ${ModelZoo_path}/trt/resnet18-5c106cde_batch8_fp16.trt
      batch_size: 8
      input_shape:
        - 3
        - 224
        - 224


build_trt_engine:
  onnx_model_path:
  input_shape: 
    - 3
    - 224
    - 224
  batch_size: -1
  calibrator: classificationEntropyCalibrator
  max_workspace_size: 1<<31
  trt_model_path: ${Build_path}/resnet18_3x224x224_b0_fp16.trt
  precision: fp16
  calibrate_cache: ${Build_path}/resnet18_3x224x224_b0_fp16.cache
  force_calibrate: true
  max_batch_size: 32
  calibrate_dir: ${Build_path}/preprocessed/resnet18_calib/
  source_dir: null


preprocess:
  dst_dir: ${Build_path}/preprocessed/
  source_dir: null
  source_file: null

preprocess_one:
  batch_size: -1
  input_shape:
    - 3
    - 224
    - 224
  mean: 
    - 0.485 
    - 0.456 
    - 0.406
  std:
    - 0.229
    - 0.224
    - 0.225
