#model_name: resnet18
#task: classification
#backbone: resnet18
#verbose: false
#debug: false
#return_path: false

rel_path: cv/classification/resnet18/resnet18_torch
ModelZoo_path: /workspace/public/basemodel/${rel_path}
SrcCode_path: ${rel_path}
Build_path: build/${rel_path}


torch:
  inherit: build_torch

build_torch:
  pretrained:
    model_path: ${ModelZoo_path}/resnet18-5c106cde.pth
  model_path: null
  verbose: true




build_onnx:
  load_pretrained: true
  torch_model_path: null
  input_shape: 
    - 3
    - 224
    - 224
  batch_size: -1
  onnx_model_path: build/cv/classification/resnet
  pretrained:
    model_path: cv/classification/resnet18/resnet18.onnx
    batch_size: -1
    input_shape:
      - 3
      - 224
      - 224
    
onnx:
  inherit: build_onnx


  
build_trt:
  precison: fp32
  input_shape: 3x224x224
  batch_size: -1
  engine_path: ${resnet18_dir_path}/resnet18.model
  force_calibrate: true
  max_batch_size: 32
  calibration_cache: './build/workspace'
  calibration_path: 'build/data'
  onnx_model_path: 'build/data'
  calibrator: simple
  preprocess_func: prefocess

