#model_name: resnet18
#task: classification
#backbone: resnet18
#verbose: false
#debug: false
#return_path: false

resnet18_src_path: cv/classification/resnet18
resnet18_build_path: null

build_torch:
  #pretrain_model_path: cv/classification/resnet18/resnet18.return_path
  #input_shape: 
  #batch_size: -1
  pretrained:
    model_path: ${resnet18_dir_path}/resnet18.pth
  model_path: null
  load_pretrained: true

torch:
  #inherit: _build_onnx
  pretrained:
    model_path: ${_build_torch.pretrained.model_path}
    batch_size: ${_build_torch.pretrained.batch_size}
  model_path: ${_build_torch.model_path}
  load_pretrained: ${_build_torch.load_pretrained}


build_onnx:
  load_pretrained: true
  torch_model_path: null
  input_shape: 
    - 3
    - 224
    - 224
  batch_size: -1
  onnx_model_path: build/cv/classification/resnet
  pretrained:
    model_path: cv/classification/resnet18/resnet18.onnx
    batch_size: -1
    input_shape:
      - 3
      - 224
      - 224
    
onnx:
  inherit: _build_onnx


  
build_trt:
  precison: fp32
  input_shape: 3x224x224
  batch_size: -1
  engine_path: ${resnet18_dir_path}/resnet18.model
  force_calibrate: true
  max_batch_size: 32
  calibration_cache: './build/workspace'
  calibration_path: 'build/data'
  onnx_model_path: 'build/data'
  calibrator: simple
  preprocess_func: prefocess

