loadNet:
  task: classification
  model_type: resnet18
  backbone: null
  mode: single
  # model: single/full


infer:
  infer_type: trt
  input_shape: null

  # infer_type: trt/onnx/torch
build_engine:
  engine_type: trt
  


torch:
  return_path: false

  
build_torch:
  model_path: null
  input_shape: 3x224x224
  batch_size: -1
  version: 1
  verbose: false
####################################
onnx:
  return_path: false
  input_shape: 
    - 3
    - 224
    - 224
  batch_size: -1
  version: 1
  opset_version: 11
  verbose: false


build_onnx:
  model_path: null
  input_shape: ${onnx.input_shape}
  batch_size: ${onnx.batch_size}
  version: 1
  opset_version: 11
  verbose: false

trt:
  return_path: false


  


preprocess:
  pass

postprocess:
  postprocess

  